# Generated by Django 2.0.1 on 2018-02-06 15:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buisness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=300, verbose_name='ව්\u200dයාපාර නාමය')),
                ('b_oname', models.CharField(max_length=100, verbose_name='අයිතිකරුගේ නම')),
                ('b_paddress1', models.CharField(max_length=100, verbose_name='අංකය')),
                ('b_paddress2', models.CharField(max_length=100, verbose_name='ලිපිනය 1')),
                ('b_paddress3', models.CharField(max_length=100, verbose_name='ලිපිනය 2')),
                ('b_type', models.CharField(max_length=300, verbose_name='ව්\u200dයාපාර ස්වභාවය')),
                ('b_sdate', models.CharField(max_length=10, verbose_name='ව්\u200dයාපාරය ආරම්භකල දිනය')),
                ('b_rnumber', models.CharField(max_length=100, verbose_name='ලියාපදිංචි අංකය')),
                ('b_tnumber', models.CharField(max_length=10, verbose_name='ව්\u200dයාපාරයේ දුරකථන අංකය')),
            ],
        ),
        migrations.CreateModel(
            name='GramasevaDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gs_province', models.CharField(choices=[('WS', 'බටහිර'), ('NR', 'නැගෙනහිර'), ('SO', 'දකුණ'), ('SB', 'සබරගමුව'), ('UV', 'උෟව'), ('CE', 'මධ්\u200dයම'), ('NC', 'උතුරුමැද'), ('NW', 'වයඹ'), ('NO', 'උතුර')], default='WS', max_length=2, verbose_name='පලාත')),
                ('gs_district', models.CharField(max_length=50, verbose_name='දිස්ත්\u200dරික්කය')),
                ('gs_divsison', models.CharField(max_length=50, verbose_name='ප්\u200dරාද්ශිය ලේකම් කොට්ඨාශය')),
                ('gs_division', models.CharField(max_length=300, verbose_name='ග්\u200dරාම නිලධාරි වසම හා අංකය')),
                ('gs_name', models.CharField(max_length=300, verbose_name='ග්\u200dරාමසේවක මහතාගේ නම')),
                ('gs_start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='සේවය පටන් ගත් දිනය')),
                ('gs_end_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 5, 15, 40, 8, 1909), verbose_name='සේවය අවසන් කල දිනය ')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_shade', models.CharField(choices=[('UL', 'උළු'), ('AS', 'ඇස්බැස්ටස්'), ('TH', 'තහඩු'), ('TS', 'තාරශීට්'), ('CO', 'කොන්ක්\u200dරීෟට්')], default='UL', max_length=20, verbose_name='වහලය')),
                ('h_floor', models.CharField(choices=[('CE', 'සිමෙන්ති'), ('TE', 'ටෙරාසෝ'), ('MB', 'මාබල්'), ('MT', 'මැටි'), ('CO', 'කොන්ක්\u200dරීට්')], default='CE', max_length=20, verbose_name='ගෙබිම')),
                ('h_wall', models.CharField(choices=[('BG', 'බලොාක් ගල්'), ('GD', 'ගඩොල්'), ('MT', 'මැටි'), ('LL', 'ලෑලි'), ('TH', 'තහඩු')], default='BG', max_length=20, verbose_name='බිත්ති')),
                ('h_water', models.BooleanField(default=False, verbose_name='ජලය')),
                ('h_elec', models.BooleanField(default=False, verbose_name='විදුලිය')),
                ('h_toilet', models.BooleanField(default=False, verbose_name='වැසිකිලි')),
                ('h_lantel', models.CharField(max_length=10, verbose_name='නිවසේ දුරකථන අංකය')),
                ('h_pic', models.ImageField(blank=True, upload_to='home_image', verbose_name='ඡායාරූපය')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_period', models.CharField(max_length=10, verbose_name='පදිංචි කාලය')),
                ('l_type', models.CharField(choices=[('SI', 'සිංනක්කර'), ('AN', 'අනවසර'), ('WB', 'වාර්ෂික බලපත්\u200dර'), ('JB', 'ජයභූමි'), ('SB', 'ස්වර්ණභූමි'), ('KU', 'කුලීකරුවන්')], default='SI', max_length=10, verbose_name='ඉඩමේ වර්ගය')),
                ('l_lno', models.CharField(max_length=10, verbose_name='බලපත්\u200dර අංකය')),
                ('l_kno', models.CharField(max_length=10, verbose_name='කට්ටි අංකය')),
                ('l_size', models.CharField(max_length=10, verbose_name='ඉඩමේ ප්\u200dරමාණය')),
                ('p_pic', models.ImageField(blank=True, upload_to='land_image', verbose_name='ඡායාරූපය')),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_name', models.CharField(max_length=300, verbose_name='සංවිධානයේ නම')),
                ('o_purpose', models.CharField(max_length=500, verbose_name='සංවිධානය වීමේ අරමුණ')),
                ('o_address1', models.CharField(max_length=100, verbose_name='සංවිධානයේ ලිපිනය')),
                ('o_address2', models.CharField(max_length=100, verbose_name='')),
                ('o_address3', models.CharField(max_length=100, verbose_name='')),
                ('o_rnumber', models.CharField(max_length=100, verbose_name='සංවිධානයේ ලියාපදිංචි අංකය')),
                ('o_sdate', models.CharField(max_length=10, verbose_name='සංවිධානය ආරම්භක දිනය')),
                ('o_nmembers', models.IntegerField(default=3, verbose_name='සමාජික සංඛ්\u200dයාව')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(choices=[('MW', 'මහවත්ත'), ('SW', 'සේදවත්ත'), ('ER', 'ඇලකන්ද පාර'), ('SR', 'සුරුවල පාර'), ('RA', 'රදැල්ල'), ('TH', 'තල්ගස්මුල්ල')], default='MW', max_length=2, verbose_name='ගම')),
                ('v_road', models.CharField(max_length=200, verbose_name='පාර')),
                ('gs_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsdivision.GramasevaDivision')),
            ],
        ),
        migrations.CreateModel(
            name='Villager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.CharField(choices=[('GM', 'ගෘහමූලික'), ('WF', 'බිරිඳ'), ('DT', 'දුව'), ('SN', 'පුතා'), ('MO', 'මව'), ('FR', 'පියා'), ('EB', 'අයියා'), ('ES', 'අක්කා'), ('ST', 'නංගි'), ('BR', 'මල්ලි'), ('SB', 'සහෝදරයා'), ('SS', 'සහෝදරිය'), ('UN', 'මාමා'), ('AN', 'නැන්දා'), ('SM', 'මෙහෙකරු'), ('SF', 'මෙහකාරිය'), ('MN', 'මුනුබුරා'), ('MI', 'මිනිබිරිය')], default='GM', max_length=2, verbose_name='ඟාති සම්බන්ධය')),
                ('p_donation', models.CharField(choices=[('EP', 'ඇස්නොපෙනන'), ('DD', 'ශ්\u200dරවන ඌණ')], default='ND', max_length=20, verbose_name='රජයෙන් ලබන ආධාර')),
                ('p_disbility', models.CharField(choices=[('EP', 'ඇස්නොපෙනන'), ('DD', 'ශ්\u200dරවන ඌණ')], default='EP', max_length=2, verbose_name='ආබාධිත')),
            ],
        ),
        migrations.AddField(
            model_name='land',
            name='h_villager',
            field=models.ManyToManyField(to='gsdivision.Villager'),
        ),
        migrations.AddField(
            model_name='house',
            name='h_villager',
            field=models.ManyToManyField(to='gsdivision.Villager'),
        ),
        migrations.AddField(
            model_name='buisness',
            name='h_villager',
            field=models.ManyToManyField(to='gsdivision.Villager'),
        ),
    ]
