# Generated by Django 2.0.1 on 2018-02-06 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsdivision', '0002_auto_20180206_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=255, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='DivisionSectOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_name', models.CharField(max_length=255, verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='gramasevadivision',
            name='gs_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 5, 15, 54, 26, 407648), verbose_name='සේවය අවසන් කල දිනය '),
        ),
    ]
