# Generated by Django 2.0.1 on 2018-02-06 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsdivision', '0005_auto_20180206_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='h_no',
            field=models.CharField(default=1, max_length=10, verbose_name='ගෘහ අංකය'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gramasevadivision',
            name='gs_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 5, 19, 16, 38, 855200), verbose_name='සේවය අවසන් කල දිනය '),
        ),
    ]
